// RideMe — i18n (ES default)
const RM_I18N_ES = {
  brand: 'RideMe', tagline: 'Tu ride, tu destino.',
  continue: 'Continuar', cancel: 'Cancelar', confirm: 'Confirmar',
  accept: 'Aceptar', reject: 'Rechazar', save: 'Guardar', back: 'Atrás',
  next: 'Siguiente', send: 'Enviar', search: 'Buscar', close: 'Cerrar',
  retry: 'Reintentar', loading: 'Cargando…', loadingMap: 'Cargando mapa…',
  seeAll: 'Ver todo', viewDetails: 'Ver detalle', edit: 'Editar',
  delete: 'Eliminar', logout: 'Cerrar sesión', skip: 'Omitir',
  rolePassenger: 'Pasajero', roleDriver: 'Conductor', roleAdmin: 'Admin',
  chooseRole: 'Elige tu rol', chooseRoleSub: 'Cambia entre pasajero y conductor cuando quieras',
  signIn: 'Iniciar sesión', signUp: 'Crear cuenta', email: 'Correo',
  phone: 'Teléfono', password: 'Contraseña', forgot: '¿Olvidaste tu contraseña?',
  orContinue: 'O continúa con', terms: 'Al continuar aceptas Términos y Política de Privacidad.',
  fullName: 'Nombre completo', noAccount: '¿No tienes cuenta?', haveAccount: '¿Ya tienes cuenta?',
  tabRides: 'Viajes', tabScheduled: 'Programados', tabMessages: 'Mensajes',
  tabProfile: 'Perfil', tabHome: 'Inicio',
  whereTo: '¿A dónde vamos?', origin: 'Origen', destination: 'Destino',
  myLocation: 'Mi ubicación', useCurrent: 'Usar ubicación actual',
  fareSuggestion: 'Sugerencia de precio', estimatedFare: 'Estimado',
  proposedFare: 'Tu precio', searchDrivers: 'Buscar conductores',
  negotiateHint: 'Puedes negociar antes de aceptar.',
  paymentMethod: 'Método de pago', cash: 'Efectivo', card: 'Tarjeta',
  schedule: 'Programar', now: 'Ahora', recent: 'Recientes', saved: 'Guardados',
  home: 'Casa', work: 'Trabajo',
  searching: 'Buscando conductores cercanos',
  searchingSub: 'Te enviaremos las ofertas en cuanto lleguen',
  expiresIn: 'Expira en', cancelRequest: 'Cancelar solicitud',
  driverOffers: 'Ofertas', noOffers: 'Sin ofertas todavía',
  noOffersSub: 'Espera unos segundos o ajusta tu precio.',
  eta: 'Llegada', etaMin: 'min', km: 'km',
  tripConfirmed: 'Viaje confirmado', tripInProgress: 'Viaje en curso',
  onTheWay: 'En camino', driverArrived: 'Conductor llegó',
  callDriver: 'Llamar', chat: 'Chat', shareTrip: 'Compartir viaje',
  tripDetails: 'Detalles del viaje', plate: 'Placas',
  agreedFare: 'Tarifa acordada', finishTrip: 'Finalizar viaje',
  rateDriver: 'Califica a tu conductor', leaveComment: 'Comentario (opcional)',
  report: 'Reportar problema', submitRating: 'Enviar',
  thanksRating: '¡Gracias por tu calificación!', goHome: 'Ir al inicio',
  rideHistory: 'Historial', completed: 'Completado', cancelled: 'Cancelado',
  filterAll: 'Todos',
  scheduledRides: 'Programados', newScheduled: 'Programar viaje',
  pickupAt: 'Recogida', noScheduled: 'No tienes viajes programados',
  noMessages: 'Sin conversaciones', typeMessage: 'Escribe un mensaje…',
  sent: 'Enviado', delivered: 'Entregado', failed: 'Error',
  myAccount: 'Mi cuenta', personalInfo: 'Datos personales',
  paymentMethods: 'Métodos de pago', security: 'Seguridad', help: 'Ayuda',
  becomeDriver: 'Ser conductor', notifications: 'Notificaciones',
  driverDashboard: 'Panel del conductor', available: 'Disponible',
  unavailable: 'Desconectado', goOnline: 'Conectarse', goOffline: 'Desconectarse',
  todayEarnings: 'Ganancias hoy', tripsCompleted: 'Viajes hoy',
  rating: 'Calificación', nearbyRequests: 'Solicitudes cercanas',
  newTripRequest: 'Nueva solicitud', submitOffer: 'Enviar oferta',
  yourPrice: 'Tu precio', goToPickup: 'Ir por pasajero',
  iArrived: 'Llegué', startTrip: 'Iniciar viaje', completeTrip: 'Finalizar viaje',
  documents: 'Documentación', uploadDoc: 'Subir documento',
  docPending: 'En revisión', docApproved: 'Aprobado', docRejected: 'Rechazado',
  docResubmit: 'Reenviar', vehicle: 'Vehículo',
  driverRegister: 'Registro de conductor', subscription: 'Suscripción',
  payoutAccount: 'Cuenta de cobro',
  adminDashboard: 'Dashboard', adminUsers: 'Usuarios', adminDrivers: 'Conductores',
  adminTrips: 'Viajes', adminPayments: 'Pagos', adminReports: 'Reportes',
  adminSettings: 'Configuración', adminAlerts: 'Alertas',
  totalUsers: 'Usuarios', activeDrivers: 'Conductores activos',
  tripsToday: 'Viajes hoy', revenue: 'Ingresos', pendingApprovals: 'Aprobaciones',
  empty: 'Nada por aquí', error: 'Algo salió mal',
  errorSub: 'No pudimos completar la acción.',
  networkError: 'Sin conexión', networkErrorSub: 'Revisa tu internet.',
  sessionExpired: 'Tu sesión expiró', signInAgain: 'Volver a iniciar',
  optional: 'opcional', minutesShort: 'min', secondsShort: 'seg',
  switchRole: 'Cambiar de rol', searchAddress: 'Busca una dirección',
  fare: 'Tarifa', distance: 'Distancia', duration: 'Duración',
  online: 'Conectado', offline: 'Desconectado',
};


// RideMe — i18n EN
const RM_I18N_EN = {
  brand: 'RideMe', tagline: 'Your ride, your way.',
  continue: 'Continue', cancel: 'Cancel', confirm: 'Confirm',
  accept: 'Accept', reject: 'Decline', save: 'Save', back: 'Back',
  next: 'Next', send: 'Send', search: 'Search', close: 'Close',
  retry: 'Retry', loading: 'Loading…', loadingMap: 'Loading map…',
  seeAll: 'See all', viewDetails: 'View details', edit: 'Edit',
  delete: 'Delete', logout: 'Sign out', skip: 'Skip',
  rolePassenger: 'Rider', roleDriver: 'Driver', roleAdmin: 'Admin',
  chooseRole: 'Choose your role', chooseRoleSub: 'Switch any time',
  signIn: 'Sign in', signUp: 'Sign up', email: 'Email',
  phone: 'Phone', password: 'Password', forgot: 'Forgot password?',
  orContinue: 'Or continue with', terms: 'By continuing you accept our Terms and Privacy Policy.',
  fullName: 'Full name', noAccount: 'No account yet?', haveAccount: 'Already have an account?',
  tabRides: 'Rides', tabScheduled: 'Scheduled', tabMessages: 'Inbox',
  tabProfile: 'Profile', tabHome: 'Home',
  whereTo: 'Where to?', origin: 'Pickup', destination: 'Destination',
  myLocation: 'My location', useCurrent: 'Use current location',
  fareSuggestion: 'Suggested price', estimatedFare: 'Est.',
  proposedFare: 'Your price', searchDrivers: 'Find drivers',
  negotiateHint: 'You can negotiate before accepting.',
  paymentMethod: 'Payment', cash: 'Cash', card: 'Card',
  schedule: 'Schedule', now: 'Now', recent: 'Recent', saved: 'Saved',
  home: 'Home', work: 'Work',
  searching: 'Looking for nearby drivers',
  searchingSub: "We'll send offers as they come in",
  expiresIn: 'Expires in', cancelRequest: 'Cancel request',
  driverOffers: 'Offers', noOffers: 'No offers yet',
  noOffersSub: 'Wait a few seconds or adjust your price.',
  eta: 'ETA', etaMin: 'min', km: 'km',
  tripConfirmed: 'Trip confirmed', tripInProgress: 'Trip in progress',
  onTheWay: 'On the way', driverArrived: 'Driver arrived',
  callDriver: 'Call', chat: 'Chat', shareTrip: 'Share trip',
  tripDetails: 'Trip details', plate: 'Plate',
  agreedFare: 'Agreed fare', finishTrip: 'Finish trip',
  rateDriver: 'Rate your driver', leaveComment: 'Comment (optional)',
  report: 'Report a problem', submitRating: 'Submit',
  thanksRating: 'Thanks for rating!', goHome: 'Go home',
  rideHistory: 'History', completed: 'Completed', cancelled: 'Cancelled',
  filterAll: 'All',
  scheduledRides: 'Scheduled', newScheduled: 'Schedule a ride',
  pickupAt: 'Pickup', noScheduled: 'No scheduled rides',
  noMessages: 'No conversations', typeMessage: 'Type a message…',
  sent: 'Sent', delivered: 'Delivered', failed: 'Failed',
  myAccount: 'My account', personalInfo: 'Personal info',
  paymentMethods: 'Payment methods', security: 'Security', help: 'Help',
  becomeDriver: 'Become a driver', notifications: 'Notifications',
  driverDashboard: 'Driver dashboard', available: 'Online',
  unavailable: 'Offline', goOnline: 'Go online', goOffline: 'Go offline',
  todayEarnings: "Today's earnings", tripsCompleted: 'Trips today',
  rating: 'Rating', nearbyRequests: 'Nearby requests',
  newTripRequest: 'New ride request', submitOffer: 'Send offer',
  yourPrice: 'Your price', goToPickup: 'Go to pickup',
  iArrived: 'I arrived', startTrip: 'Start trip', completeTrip: 'Complete trip',
  documents: 'Documents', uploadDoc: 'Upload document',
  docPending: 'In review', docApproved: 'Approved', docRejected: 'Rejected',
  docResubmit: 'Resubmit', vehicle: 'Vehicle',
  driverRegister: 'Become a driver', subscription: 'Subscription',
  payoutAccount: 'Payout account',
  adminDashboard: 'Dashboard', adminUsers: 'Users', adminDrivers: 'Drivers',
  adminTrips: 'Trips', adminPayments: 'Payments', adminReports: 'Reports',
  adminSettings: 'Settings', adminAlerts: 'Alerts',
  totalUsers: 'Users', activeDrivers: 'Active drivers',
  tripsToday: 'Trips today', revenue: 'Revenue', pendingApprovals: 'Approvals',
  empty: 'Nothing here', error: 'Something went wrong',
  errorSub: "We couldn't complete the action.",
  networkError: 'No connection', networkErrorSub: 'Check your internet.',
  sessionExpired: 'Session expired', signInAgain: 'Sign in again',
  optional: 'optional', minutesShort: 'min', secondsShort: 'sec',
  switchRole: 'Switch role', searchAddress: 'Search an address',
  fare: 'Fare', distance: 'Distance', duration: 'Duration',
  online: 'Online', offline: 'Offline',
};
